### ISSUE TITLE
Not working under HA 2025.06

### ISSUE THREAD

**Issue by KixMan28** [vorostamas/portHuTV-homeassistant#23]
## Version of the custom_component
1.0.8

## Configuration

```yaml

Add your configuration here.

```

## Describe the bug
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:335
First occurred: 12:56:50 (1 occurrence)
Last logged: 12:56:50

Detected that custom integration 'porthutv' sets option flow config_entry explicitly, which is deprecated at custom_components/porthutv/config_flow.py, line 85: self.config_entry = config_entry. This will stop working in Home Assistant 2025.12, please create a bug report at https://github.com/vorostamas/porthutv/issues

## Debug log

```
Logger: homeassistant.config_entries
Source: config_entries.py:749
First occurred: 13:35:36 (21 occurrences)
Last logged: 13:35:38

Error setting up entry Cinemax 2 for porthutv
Error setting up entry Film Mánia for porthutv
Error setting up entry Paramount Network for porthutv
Error setting up entry VIASAT6 for porthutv
Error setting up entry Comedy Central for porthutv
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/porthutv/__init__.py", line 63, in async_setup_entry
    hass.config_entries.async_forward_entry_setup(entry, platform)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
```
Logger: homeassistant.core
Source: helpers/deprecation.py:222
First occurred: 13:35:36 (1 occurrence)
Last logged: 13:35:36

Config was used from porthutv, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'porthutv' custom integration
